/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TodoItem } from "./components/todo-list/todo-list";
import { TreeNode } from "./components/tree-view/tree-view";
export { TodoItem } from "./components/todo-list/todo-list";
export { TreeNode } from "./components/tree-view/tree-view";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TodoList {
        "addItem": (desc: string) => Promise<TodoItem[]>;
        "header": string;
        "list": TodoItem[];
    }
    interface TreeView {
        "data": TreeNode[];
        "expanded": boolean;
    }
}
export interface TodoListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTodoListElement;
}
export interface TreeViewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTreeViewElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLTreeViewElement extends Components.TreeView, HTMLStencilElement {
    }
    var HTMLTreeViewElement: {
        prototype: HTMLTreeViewElement;
        new (): HTMLTreeViewElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "todo-list": HTMLTodoListElement;
        "tree-view": HTMLTreeViewElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TodoList {
        "header"?: string;
        "list"?: TodoItem[];
        "onTodoAdded"?: (event: TodoListCustomEvent<TodoItem>) => void;
        "onTodoCompleted"?: (event: TodoListCustomEvent<TodoItem>) => void;
    }
    interface TreeView {
        "data"?: TreeNode[];
        "expanded"?: boolean;
        "onToggleNode"?: (event: TreeViewCustomEvent<{node: TreeNode, expand: boolean }>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "todo-list": TodoList;
        "tree-view": TreeView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
            "tree-view": LocalJSX.TreeView & JSXBase.HTMLAttributes<HTMLTreeViewElement>;
        }
    }
}
